export const data = [
    {
        name: "Math Assessment",
        type: "Job",
        time: "20 Apr 23",
        duration: "00",
        questions: "00",
        numbers: "0",
    },
    {
        name: "Math Assessment",
        type: "Job",
        time: "20 Apr 23",
        duration: "00",
        questions: "00",
        numbers: "324",
    },
    {
        name: "Math Assessment",
        type: "Job",
        time: "20 Apr 23",
        duration: "00",
        questions: "00",
        numbers: "324",
    },
    {
        name: "Math Assessment",
        type: "Job",
        time: "20 Apr 23",
        duration: "00",
        questions: "00",
        numbers: "324",
    },
    {
        name: "Math Assessment",
        type: "Job",
        time: "20 Apr 23",
        duration: "00",
        questions: "00",
        numbers: "324",
    },
    {
        name: "Math Assessment",
        type: "Job",
        time: "20 Apr 23",
        duration: "00",
        questions: "00",
        numbers: "324",
    },
    {
        name: "Math Assessment",
        type: "Job",
        time: "20 Apr 23",
        duration: "00",
        questions: "00",
        numbers: "32,4090",
    },
];
